### ISSUE TITLE
"cert-manager" has no deployed releases

### ISSUE THREAD

**Issue by tsu84** [particuleio/teks#100]
I'm trying to run EKS, and after many errors, I get to finish the apply once.

Now, if I try to destroy or to apply again, it shows always this error:
```
helm_release.cert-manager[0]: Modifying... [id=cert-manager]
>
> Error: "cert-manager" has no deployed releases
> 
>   with helm_release.cert-manager[0],
>   on cert-manager.tf line 117, in resource "helm_release" "cert-manager":
> 117: resource "helm_release" "cert-manager" {
```

Someone had the same issue?

**Comment by ArchiFleKs** [comment]
There must have been an issue with the installation, could you provide more details ?

As a workaround you can  `helm -n cert-manager delete cert-manager` and `terragrunt apply` to reinstall

**Comment by ArchiFleKs** [comment]
@tsu84 closing for now. Feel free to reopen if needed
