### ISSUE TITLE
Custom VPC endponts list and the module resources?

### ISSUE THREAD

**Issue by bd-spl** [particuleio/teks#101]
When deploying w/o NAT gateway, what is the expected pattern for giving a list of required VPC endpoints, with EKS cluster security group ID(s) and policies (aws_iam_policy_document) maybe?

To my understanding, [endpoints](https://github.com/particuleio/teks/blob/a8d54eebf418887b79847fab50a54634ee52192c/terragrunt/live/production/eu-west-1/clusters/demo/vpc-endpoints/terragrunt.hcl#L19) would be the right place to add it there?

FTR, I want to follow that [guide](https://k8s-dev.medium.com/setup-a-fully-private-amazon-eks-on-aws-fargate-cluster-514f775d69f) to deploy on a private VPC and Fargate workers instead of EC2, so I need the following PrivateLinks (VPC endpoints):
* Interface endpoints for ECR (both ecr.api and ecr.dkr) to pull container images
* A gateway endpoint for S3 to pull the actual image layers
* An interface endpoint for EC2
* An interface endpoint for STS to support Fargate and IAM Roles for Services Accounts
* An interface endpoint for CloudWatch logging (logs) if CloudWatch logging is required

What I couldn't get is, how/should I specify other module inputs for endpoints then: [aws_iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document) and [security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/security_group), like it is shown in [example](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/75911a9bcdfd6a2452afa69d32175c2ebd4ad784/modules/vpc-endpoints/README.md#L10)?

Please confirm if that can be done like that:
* the rules defined in [node_security_group_additional_rules](https://github.com/particuleio/teks/blob/c5d0ba34c0ca93ed4dbf336e6a1485eec2ebc71c/terragrunt/live/production/eu-west-1/clusters/demo/eks/terragrunt.hcl#L99), merged with defaults that terraform-eks-aws provides via local [cluster_security_group_rules](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e0f5995a8b08b89cc6e805a9874d8265230b6a93/main.tf#L94), should be pre-created by tEKS. And then passed into terraform-aws-eks via external ``cluster_security_group_id = "sg-xxxx"`` and setting ``create_cluster_security_group = false``

**Comment by ArchiFleKs** [comment]
@bd-spl I think you need to play with the vpc-endpoint module, each endpoint can reference a security group. To avoid dependencies loop, the best think would be to use the default vpc security group for endpoints which allowed 0.0.0.0/0 in teks default. And then switch to allow the cluster security group

**Comment by ArchiFleKs** [comment]
@bd-spl I'll close this for now, could you please reopen in [Discussions](https://github.com/particuleio/teks/discussions) as it is not technically tEKS issue
