### ISSUE TITLE
EKS Cluster creation failed in region us-east-1

### ISSUE THREAD

**Issue by amitkarpe** [particuleio/teks#11]
Hi,

Thank you for a great project.
While I was following getting started guide, I did not fully understand the procedure.

```
 ➜ tg apply -auto-approve
[terragrunt] [/Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/eks] 2021/01/27 17:19:49 Running command: terraform --version
[terragrunt] 2021/01/27 17:19:49 Terraform version: 0.14.5
[terragrunt] 2021/01/27 17:19:49 Reading Terragrunt config file at /Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/eks/terragrunt.hcl
[terragrunt] [/Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/vpc] 2021/01/27 17:19:49 Generated file /Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/vpc/.terragrunt-cache/569303351/backend.tf.
[terragrunt] [/Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/vpc] 2021/01/27 17:19:49 Running command: terraform init -get=false -get-plugins=false
[terragrunt] [/Users/amitkarpe/code/terraform/tg/first/teks/terragrunt/live/mycluster/us-east-1/clusters/full/vpc] 2021/01/27 17:19:53 Running command: terraform output -json
Failed to load state: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-3'
	status code: 400, request id: E0C2281C2098748E, host id: yOzy5JSeIdmHlj/m2M+rkKD9KY86uCrLQ+1xtp+Rp+jmYFYVaDmixcwaiy3KdvvcwKxLWkFvEJ0=
[terragrunt] 2021/01/27 17:20:01 exit status 1
```

I created cloned [here](https://github.com/mytestlab123/teks/tree/main/terragrunt/live/mycluster/us-east-1/clusters/full/eks), copied demo into mycluster folder.
While running terragrunt apply, it failed with the above errors. Can you please let me know how to follow the guide?

Also, I want to know do you have a slack channel or any community forum to a discussion about further contribution?

**Comment by ArchiFleKs** [comment]
@amitkarpe Hi and thanks for your feedback, what module are you running here ? VPC, EKS or EKS-addons ? 

I recently deployed two clusters with this setup on different region in `eu-west-1` and `eu-west-3`. How did you create the S3 bucket ? is it created by Terragrunt or did you create it before ? 

Can you check the location of the bucket ? It tries to load the state but failed because it tries the `us-east-1` region but the bucket might be in `eu-west-3`

I'm available to chat in the [Kubernetes slack channel](https://slack.k8s.io/), my handle is ArchiFleKS

**Comment by amitkarpe** [comment]
Hi @ArchiFleKs,

I was wrong. When I create s3 bucket in us-east-1, it started working.
I will try to update the guide with PR. Thank you for your fast response.
