### ISSUE TITLE
block_device_mappings.0.ebs.0.kms_key_id" (arn:::aws) is an invalid ARN: arn: not enough sections

### ISSUE THREAD

**Issue by fabiocruzcoelho** [particuleio/teks#125]
Hi, I'm using your project to create an eks cluster, but I'm having this error., can you explain if I'm doing something wrong?

Error: "block_device_mappings.0.ebs.0.kms_key_id" (arn:::aws) is an invalid ARN: arn: not enough sections
 
   with module.eks_managed_node_group["default-a"].aws_launch_template.this[0],
   on modules/eks-managed-node-group/main.tf line 45, in resource "aws_launch_template" "this":
   45: resource "aws_launch_template" "this" {
 

 Error: "block_device_mappings.1.ebs.0.kms_key_id" (arn:::aws) is an invalid ARN: arn: not enough sections
 
   with module.eks_managed_node_group["default-a"].aws_launch_template.this[0],
   on modules/eks-managed-node-group/main.tf line 45, in resource "aws_launch_template" "this":
   45: resource "aws_launch_template" "this" {

**Comment by fabiocruzcoelho** [comment]
passed after I changed the line in encryption-config.hcl

```
from:
mock_outputs = {
    arn = "arn:::aws"
  }

to:
  mock_outputs = {
    arn = "arn:aws:iam::111122223333:root"
  }
```

**Comment by ArchiFleKs** [comment]
> passed after I changed the line in encryption-config.hcl
> 
> ```
> from:
> mock_outputs = {
>     arn = "arn:::aws"
>   }
> 
> to:
>   mock_outputs = {
>     arn = "arn:aws:iam::111122223333:root"
>   }
> ```

Hi sorry for the delay, could you make a PR to update the mock output with the correct number of `:` please ?
