### ISSUE TITLE
Multi Cloud Support

### ISSUE THREAD

**Issue by zestrells** [particuleio/teks#126]
Hi Particule IO Team!

We are getting ready to implement terragrunt and kubernetes in Azure and/or GCP. We love what you have done with teks and appreciate all the hard work. Is there anyway you have suggestions or a template / way of doing teks and terragrunt for Azure and GCP? 

Thank you for all your support so far!

- Zach

**Comment by ArchiFleKs** [comment]
Hi @zestrells , I wanted to do this for a long time (but lack of time ...). I'd go the same way with GCP and official modules:
* https://github.com/terraform-google-modules/terraform-google-kubernetes-engine
* https://github.com/terraform-google-modules/terraform-google-network

And then add to terraform-kubernetes-addons the required addons integrated with https://github.com/terraform-google-modules/terraform-google-service-accounts, just like IAM role for services account.

I'm all for adding feature to addons in Azure and GCP.

For Azure I'm less familiar with official modules to be honest.

My goal you be to have a `t` repository just like tEKS but with multi cloud support (we already do that for some customers on AWS/Scaleway) with the same structure as tEKS but with higher level

iac/
iac/aws
iac/gcp
iac/azure

And then you can still have mergable global values between environment and also get output from other cloud etc with Terragrunt.

**Comment by ArchiFleKs** [comment]
Hi @zestrells I will close this for now, if you have any more questions could you please move this to [Discussions](https://github.com/particuleio/teks/discussions)
