### ISSUE TITLE
VPC dependency datasources error

### ISSUE THREAD

**Issue by fabiocruzcoelho** [particuleio/teks#128]
Hello
Hello, I'm trying to use your template to create an eks cluster, but when I run the terragrunt plan command from the vpc directory, it returns the error below.

`datasources is a dependency of /home/user/projects/vitta/terraform-live/aws-eks/development/us-east-1/vpc/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block. `

even running the command `terragrunt run-all plan` I got the same error.

I tried adding the` skip_outputs` flag to true on the dependency block, but without success.

could you let me know if I'm doing something wrong, I'm following the readme but still not getting success

**Comment by ArchiFleKs** [comment]
@fabiocruzcoelho Yes terragrunt plans are tricky to get to work with outputs, I'll see to add more outputs
