### ISSUE TITLE
demo cluster is not working

### ISSUE THREAD

**Issue by zestrells** [particuleio/teks#62]
Hello All,
I am trying to spin up the demo cluster and by default, it is not working to create the managed worker nodes. Is this a bug in the latest AMI? Or is it an issue with something I am doing?

**Comment by ArchiFleKs** [comment]
Could you post some logs here ?

**Comment by zestrells** [comment]
> Could you post some logs here ?

Well, basically there is no logs. Once the instance launches in the node group, it never becomes healthy.

**Comment by zestrells** [comment]
It looks like when I make entries to the aws-auth with users and roles. It removes the access for everything to work. See here
```
Your worker nodes do not have access to the cluster. Verify if the node instance role is present and correctly configured in the aws-auth ConfigMap.
```

**Comment by ArchiFleKs** [comment]
@zestrells AWS auth part is broken, will fix asap
