### ISSUE TITLE
Critical Pods (nginx-ingress, calico-node...) fail readiness checks under CPU pressure

### ISSUE THREAD

**Issue by Neki** [particuleio/teks#7]
Hi,

With the configuration provided in this repo, when a (user-scheduled) Pod without CPU limits puts a lot of CPU pressure on a node, critical pods are denied the CPU shares required to correctly pass readiness or even liveliness checks (I've observed this in production, this is reproducible).
This results in nginx-ingress, calico-node and kiam not receiving traffic, or even restarting.

I've noticed that
* calico-node
* kiam
* nginx-ingress

do not have CPU requests set. I guess that's the reason why the health checks timeout under CPU pressure.

Should we add CPU requests for all these Pods? Is there a better way to fix this issue?

Thanks!

**Comment by ArchiFleKs** [comment]
@Neki Yes we could add a sensible default in the helm chart defaults values
