### ISSUE TITLE
Couldn't find EKS resource

### ISSUE THREAD

**Issue by BehbudSh** [particuleio/teks#74]
Hi, could u please help me to find out how to properly define a data source for cluster critical addons? I'm getting this error on terragrunt run-all plan command
`Error: error reading EKS Cluster (cluster-name): couldn't find resource
│ 
│   with data.aws_eks_cluster.cluster,
│   on provider-local.tf line 22, in data "aws_eks_cluster" "cluster":
│   22:   data "aws_eks_cluster" "cluster" {`

and this is my critical addons terragrunt.hcl file
`
  include "root" {
    path           = find_in_parent_folders()
  }
  terraform {
    source = "${get_parent_terragrunt_dir()}/_modules/remote/critical_addons/modules/aws"
  }

  locals {
    environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
    region_vars = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  
    env                                               = local.environment_vars.locals.environment
    general_name                              = local.environment_vars.locals.general_name
    mock_commands                         = local.environment_vars.locals.mock_commands
    cluster_version                             = local.environment_vars.locals.cluster_version
    region                                          = local.region_vars.locals.aws_region
    extra_values                                 = local.environment_vars.locals.extra_values
    kube_system_namespace            = local.environment_vars.locals.kube_system_namespace
  }

  generate "provider" {
    path      = "provider-local.tf"
    if_exists = "overwrite"
    contents  = <<EOF
  provider "kubernetes" {
    host                           = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
    token                         = data.aws_eks_cluster_auth.cluster.token
  }

  provider "kubectl" {
   host                           = data.aws_eks_cluster.cluster.endpoint
   cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
   token                         = data.aws_eks_cluster_auth.cluster.token
  }

  provider "helm" {
   kubernetes {
     host                   = data.aws_eks_cluster.cluster.endpoint
     cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
     token                  = data.aws_eks_cluster_auth.cluster.token
   }
  }

  data "aws_eks_cluster" "cluster" {
    name = var.cluster-name
  }
  
  data "aws_eks_cluster_auth" "cluster" {
    name = var.cluster-name
  }
  EOF
  }

  dependency "eks" {
    config_path = find_in_parent_folders("eks")

    mock_outputs_allowed_terraform_commands = local.mock_commands
    mock_outputs = {
      cluster_id              = "cluster-name"
      cluster_oidc_issuer_url = "https://oidc.eks.us-east-1.amazonaws.com/id/0000000000000000"
    }
  }
  
 dependency "vpc" {
   config_path = find_in_parent_folders("vpc")

   mock_outputs_allowed_terraform_commands = local.mock_commands
   mock_outputs = {
    private_subnets_cidr_blocks = ["fake","fake"]
   }
  }

 dependencies {
   paths = ["../iam/oidc"]
  }

  inputs = {
    cluster-name = dependency.eks.outputs.cluster_id
  
    eks = {
      "cluster_oidc_issuer_url" = dependency.eks.outputs.cluster_oidc_issuer_url
    }
  
    metrics-server = {
      enabled       = true
      extra_values  = local.extra_values
      namespace     = local.kube_system_namespace
      allowed_cidrs = dependency.vpc.outputs.private_subnets_cidr_blocks
    }
  
    cluster-autoscaler = {
      enabled       = true
      namespace     = local.kube_system_namespace
      extra_values  = local.extra_values 
    }

    keda = {
      enabled          = true
      extra_values     = local.extra_values 
      create_ns        = true
    }
  }`

**Comment by ArchiFleKs** [comment]
Hi. I'm not sure what you are trying to do, do you have a repo with an config example ?
