### ISSUE TITLE
Error when running terragrunt plan in the EKS Module

### ISSUE THREAD

**Issue by DanielNetzeriAm** [particuleio/teks#9]
First I would like to thank for this great repository and the code here, it's pure gold.

Sadly I'm experiencing an error which for a beginner like me isn't very simple to find out why it happens.

Error: Failed to instantiate provider "kubectl" to obtain schema: fork/exec /Users/dnetzer/Repositories/Vonage/vgai-studio-infra/live/dev/eu-west-1/eks/.terragrunt-cache/Ug5X0EQf-ySvHn_k0tDzaYfjHuo/vo8pQqWUeCu_1_TBy7LGvx51SW0/terraform-provider-kubectl: exec format error

This is the error I get when I run `terragrunt plan`, after I run a successful `terragrunt init` in the EKS module.
I tried using kubectl 1.17.11 (similar to what you use in the repo), and I've tried with 19.0.0 (latest stable).

EDIT 1:
updated terragrunt to v0.23.40 which uses terraform v0.13.2, and now when I run `terragrunt init` it fails with the following error:

Error: Failed to install provider

Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl

Any help would be much appreciated.

**Comment by ArchiFleKs** [comment]
The repo has quite change since last time, if you want to try again and are still experiencing issue please reopen
